server {
    listen 80;
    listen [::]:80;
    server_name ia.rafinha.dev;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ia.rafinha.dev;

    root /var/www/ia.rafinha.dev/current/public;

    ssl_certificate /etc/nginx/ssl/ia.rafinha.dev.crt;
    ssl_certificate_key /etc/nginx/ssl/ia.rafinha.dev.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        include /etc/nginx/snippets/ia.rafinha.dev.proxy.conf;
        proxy_pass http://127.0.0.1:3120;
    }
}
